spring:
  application:
    name: "auth-template"

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  banner:
    location: banner.txt

  codec:
    max-in-memory-size: 50MB

  webflux:
    base-path: /api/v1
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  compression:
    enabled: false

  http2:
    enabled: false

security:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: ${JWT_EXPIRATION}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.apache.kafka: OFF
    org.quartz: OFF
    org.apache.kafka:clients.NetworkClient: OFF
    org.springframework.scheduling.quartz.LocalDataSourceJobStore: OFF

server:
  port: ${PORT}

